name: 'Deploy with kustomize'
description: 'This action compiles your kustomize manifests and deploys it with kubectl'
inputs:
  registry:
    description: ''
    required: true
  images:
    description: ''
    required: false
  overlay:
    description: ''
    required: true
  monitoring:
    description: ''
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'